# Generated by Django 2.1.5 on 2019-04-07 09:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacsy',
            fields=[
                ('codebs', models.CharField(default='', max_length=5, primary_key=True, serialize=False, verbose_name='Code:')),
                ('hoten', models.CharField(default='', max_length=200, verbose_name='Họ tên:')),
                ('diachi', models.CharField(default='', max_length=200, verbose_name='Địa chỉ:')),
                ('thanhpho', models.CharField(default='', max_length=200, verbose_name='Thành phố:')),
                ('mobile', models.CharField(default='', max_length=200, verbose_name='Mobile')),
                ('email', models.CharField(default='', max_length=200, verbose_name='Email:')),
                ('sochungchihanhnghe', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Số Chứng chỉ hành nghề:')),
                ('nghiepvu', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chuyên khoa')),
                ('chucdanh', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Chức danh')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date ngày tham gia')),
            ],
            managers=[
                ('bsy', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Benhan',
            fields=[
                ('cba', models.CharField(default='', max_length=5, primary_key=True, serialize=False, verbose_name='Code:')),
                ('dnv', models.DateField(default=datetime.date.today, verbose_name='Date ngày nhập viện')),
                ('dxv', models.DateField(default=datetime.date.today, verbose_name='Date ngày xuất viện')),
                ('dttvp', models.DateField(default=datetime.date.today, verbose_name='Date ngày thanh toán viện phí')),
            ],
            managers=[
                ('ban', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Benhsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbx', models.TextField(max_length=200, verbose_name='Tên bệnh sử')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Ngày nhập dữ liệu:')),
                ('cba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Benhan')),
            ],
            managers=[
                ('bs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dichvuyeucau',
            fields=[
                ('cdv', models.CharField(default='', max_length=5, primary_key=True, serialize=False, verbose_name='Code:')),
                ('tdv', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('tt', models.CharField(default='1', max_length=2, verbose_name='Trạng thái')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('cba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Benhan')),
            ],
            managers=[
                ('dv', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('codediv', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='Code trung tâm')),
                ('namediv', models.CharField(max_length=200, verbose_name='Tên trung tâm ')),
            ],
            managers=[
                ('div', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Donthuoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.CharField(default='1', max_length=200, verbose_name='Số lượng ')),
                ('dvtinh', models.CharField(default='vỉ', max_length=200, verbose_name='Đơn vị tính')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            managers=[
                ('Donthuoc1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Donthuocdieutri',
            fields=[
                ('cdtdt', models.CharField(default='', max_length=5, primary_key=True, serialize=False, verbose_name='Code:')),
                ('sl', models.CharField(default='1', max_length=200, verbose_name='Số lượng ')),
                ('dvt', models.CharField(default='vỉ', max_length=200, verbose_name='Đơn vị tính')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='ngày kê đơn')),
                ('cba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Benhan')),
            ],
            managers=[
                ('dtdt', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ketluan',
            fields=[
                ('codeketluan', models.CharField(default='', max_length=200, primary_key=True, serialize=False, verbose_name='Code kết luận')),
                ('name_ketluan', models.TextField(blank=True, null=True, verbose_name='Kết luận ')),
                ('bacsy', models.CharField(max_length=200, verbose_name='Bác sỹ')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            managers=[
                ('ketluan1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Kieu_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khachhang', models.BooleanField(default=False)),
                ('bacsy', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('nhanvien_trungtam', models.BooleanField(default=False)),
                ('nhanvien_data', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('kieuuser', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('codemedicine', models.CharField(default='K', max_length=200, primary_key=True, serialize=False, verbose_name='Code medicine')),
                ('thc', models.CharField(default='', max_length=200, verbose_name='Tên hoạt chất')),
                ('tbd', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Tên biệt dược')),
                ('dvt', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Đơn vị tính')),
                ('ttct', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='thông tin chi tiết')),
                ('on_off', models.BooleanField(default=True)),
            ],
            managers=[
                ('medi', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('codepatientp', models.CharField(default='BN1', max_length=10, primary_key=True, serialize=False, verbose_name='Code bệnh nhân')),
                ('namepatient', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('age', models.IntegerField(default=40, verbose_name='Tuổi')),
                ('place', models.CharField(max_length=200, null=True, verbose_name='Địa chỉ')),
                ('City', models.CharField(default='Hà Nội', max_length=200, null=True, verbose_name='Thành phố')),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Division')),
            ],
            managers=[
                ('pat', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Phongthuoctrungtam',
            fields=[
                ('maphong', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='Code phong')),
                ('tenphong', models.CharField(blank=True, default='', max_length=200, verbose_name='Tên phong ')),
                ('trungtam9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Division')),
            ],
            managers=[
                ('phongm', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quanlyuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin1', models.BooleanField(default=False)),
                ('phong', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='center.Phongthuoctrungtam')),
                ('trungtam', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='center.Division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('qluser', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Đã gửi yêu cầu', max_length=200, verbose_name='Trạng thái')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Ngày yêu cầu dịch vụ')),
                ('codepatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient')),
            ],
            managers=[
                ('serv', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='tên trang:')),
            ],
            managers=[
                ('ttrang', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trieuchung',
            fields=[
                ('codetrieuchung', models.CharField(default='', max_length=200, primary_key=True, serialize=False, verbose_name='Code triệu chứng')),
                ('trieuchung1', models.CharField(default='Bất tỉnh', max_length=200, verbose_name='Triệu chứng')),
                ('nhomcoquan', models.CharField(default='Bất tỉnh', max_length=200, verbose_name='Nhóm cơ quan')),
                ('on_off', models.BooleanField(default=True)),
            ],
            managers=[
                ('tchung', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trieuchungbenhnhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.CharField(default='1', max_length=2, verbose_name='Trạng thái')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('cba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Benhan')),
                ('ctt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Trieuchung')),
            ],
            managers=[
                ('tcbn', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trieuchungcb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.CharField(default='1', max_length=2, verbose_name='Trạng thái')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('codepatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient')),
                ('codetrieuchung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Trieuchung')),
            ],
            managers=[
                ('tccucbo', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trieuchungtq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.CharField(default='1', max_length=2, verbose_name='Trạng thái')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('codepatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codepatienttctq', to='center.Patient')),
                ('codetrieuchung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codetctqs', to='center.Trieuchung')),
            ],
            managers=[
                ('trieuchungtqs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Typekhancap',
            fields=[
                ('codekc', models.CharField(default='DV', max_length=12, primary_key=True, serialize=False, verbose_name='Code service')),
                ('tenxlkc', models.CharField(max_length=200, verbose_name='Tên xử lý khẩn cấp ')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('on_off', models.BooleanField(default=True)),
            ],
            managers=[
                ('typekc', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Typeservice',
            fields=[
                ('codeservice', models.CharField(default='DV', max_length=12, primary_key=True, serialize=False, verbose_name='Code service')),
                ('name_serv', models.CharField(max_length=200)),
                ('on_off', models.BooleanField(default=True)),
            ],
            managers=[
                ('typeserv', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht', models.CharField(blank=True, default='', max_length=200, verbose_name='Họ tên:')),
                ('gioitinh', models.CharField(blank=True, default='Ông', max_length=3, verbose_name='Giới tinh')),
                ('dc', models.CharField(blank=True, default='', max_length=200, verbose_name='Địa chỉ:')),
                ('tp', models.CharField(blank=True, default='', max_length=200, verbose_name='Thành phố:')),
                ('mb', models.CharField(blank=True, default='', max_length=200, verbose_name='Mobile')),
                ('em', models.CharField(blank=True, default='', max_length=200, verbose_name='Email:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('kh', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Xlkhancap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_xlkc', models.CharField(max_length=200, verbose_name='Tên xử lý khẩn cấp ')),
                ('status', models.CharField(default='Đã gửi yêu cầu', max_length=200, verbose_name='Trạng thái')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('codepatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient')),
            ],
            managers=[
                ('Xlkhancap1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Xuly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txl', models.CharField(max_length=200, verbose_name='Tên xử lý khẩn cấp')),
                ('tt', models.CharField(default='1', max_length=2, verbose_name='Trạng thái')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('cba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Benhan')),
            ],
            managers=[
                ('xl', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Yeucau',
            fields=[
                ('cyc', models.CharField(default='', max_length=5, primary_key=True, serialize=False, verbose_name='Code:')),
                ('tdv', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('cl', models.CharField(default='1', max_length=2, verbose_name='Chất lượng')),
                ('tt', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Ngày yêu cầu')),
                ('bs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Bacsy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('yc', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='codeservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Typeservice'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Phongthuoctrungtam'),
        ),
        migrations.AddField(
            model_name='ketluan',
            name='codepatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient'),
        ),
        migrations.AddField(
            model_name='donthuocdieutri',
            name='ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Medicine'),
        ),
        migrations.AddField(
            model_name='donthuoc',
            name='codedonthuoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Medicine'),
        ),
        migrations.AddField(
            model_name='donthuoc',
            name='codepatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient'),
        ),
        migrations.AddField(
            model_name='benhan',
            name='bn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient'),
        ),
        migrations.AddField(
            model_name='benhan',
            name='bs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Bacsy'),
        ),
    ]
