# Generated by Django 2.2 on 2019-04-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_patient_bacsy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donthuoc',
            name='dvtinh',
        ),
        migrations.RemoveField(
            model_name='donthuoc',
            name='lankham',
        ),
    ]
