# Generated by Django 2.2 on 2019-04-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20190429_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='donthuoc',
            name='huongdan',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Hướng dẫn'),
        ),
        migrations.AlterField(
            model_name='donthuoc',
            name='soluong',
            field=models.CharField(blank=True, default='1', max_length=200, null=True, verbose_name='Số lượng '),
        ),
    ]
