# Generated by Django 2.2 on 2019-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20190430_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donthuoc',
            name='huongdan',
            field=models.CharField(default='', max_length=255, verbose_name='Hướng dẫn'),
        ),
        migrations.AlterField(
            model_name='donthuoc',
            name='soluong',
            field=models.CharField(default='1', max_length=200, verbose_name='Số lượng '),
        ),
    ]
