# Generated by Django 2.2 on 2019-05-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_loggeduser_tp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user0',
            name='gioitinh',
        ),
    ]
