# Generated by Django 2.2 on 2019-05-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_auto_20190501_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yeucau',
            name='cyc',
        ),
        migrations.RemoveField(
            model_name='yeucau',
            name='tt',
        ),
        migrations.AddField(
            model_name='yeucau',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yeucau',
            name='ma_thanhtoan_v',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Mã thanh toan:'),
        ),
        migrations.AddField(
            model_name='yeucau',
            name='thanhtoan_v',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='thanhtoan'),
        ),
        migrations.AlterField(
            model_name='yeucau',
            name='cl',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Chất lượng'),
        ),
        migrations.AlterField(
            model_name='yeucau',
            name='tdv',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Tên dịch vụ'),
        ),
    ]
