# Generated by Django 2.2 on 2019-05-02 03:11

import center.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0013_auto_20190502_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeucau',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=models.SET(center.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
