# Generated by Django 2.2 on 2019-05-02 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0016_auto_20190502_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeucau',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL),
        ),
    ]
