# Generated by Django 2.2 on 2019-05-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0020_auto_20190502_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeucau',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
